name: PHP Quality Assurance
on: [push, pull_request]
jobs:
    QA:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"

        strategy:
            matrix:
                php: ['7.0', '7.1', '7.2', '7.3', '7.4']
                dependencies:
                    - "lowest"
                    - "highest"
                experimental:
                    - false
                include:
                    - php: "8.0"
                      dependencies: "highest"
                      composer-options: "--ignore-platform-reqs"
                      experimental: true

        continue-on-error: ${{ matrix.experimental }}

        steps:
            - uses: actions/checkout@v2

            - name: Setup PHP version
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}

            - name: Check syntax error in sources
              run: find ./src/ ./tests/src/ ./tests/cases/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

            - name: Install dependencies
              run: composer install -q -n -a --no-progress --prefer-dist
              if: ${{ matrix.php < 8 }}

            - name: Install dependencies
              run: composer install -q -n -a --no-progress --prefer-dist --ignore-platform-reqs
              if: ${{ matrix.php >= 8 }}

            - name: Run unit tests (>= 7.3)
              if: ${{ matrix.php >= 7.3 }}
              run: ./vendor/bin/phpunit --migrate-configuration

            - name: Run unit tests (< 7.3)
              if: ${{ matrix.php-versions < 7.3 }}
              run: ./vendor/bin/phpunit

            - name: Check code styles
              if: ${{ matrix.php == '7.4' }}
              run: ./vendor/bin/phpcs

            - name: Check cross-version PHP compatibility
              if: ${{ matrix.php-versions == '7.4' }}
              run: composer phpcompat

            - name: Check Psalm
              if: ${{ matrix.php == '7.4' }}
              run: ./vendor/bin/psalm
