name: PHP Quality Assurance
on: [push, pull_request]
jobs:
    QA:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip')"

        strategy:
            matrix:
                php: ['7.0', '7.1', '7.2', '7.3', '7.4']
                dependencies:
                    - "lowest"
                    - "highest"
                experimental:
                    - false
                include:
                    - php: "8.0"
                      dependencies: "highest"
                      composer-options: "--ignore-platform-reqs"
                      experimental: true

        continue-on-error: ${{ matrix.experimental }}

        steps:
            -   uses: actions/checkout@v2

            -   name: Setup PHP version
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}

            -   name: Check syntax error in sources
                run: find ./src/ ./tests/src/ ./tests/cases/ -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l

            -   name: Install dependencies
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "${{ matrix.composer-options }}"
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: Run unit tests
                run: ./vendor/bin/phpunit

            -   name: Check code styles
                run: ./vendor/bin/phpcs

            -   name: Check Psalm
                run: ./vendor/bin/psalm
